server:
  port: 8081
spring:
  application:
    name: dpdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: mpw:BkmVuJAQLIElCPHgP7oZcw==
    password: mpw:4rwSv6pvNYGinHh8iT0Fpg==
  redis:
    host: mpw:6x/KCx1f7z2LoUtgmzcL7Q==
    port: 6379
    #password: jhs9uas8G3imcMLD5xwozg==
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dpdp.entity # 别名扫描包(com.dpdp.entity包类的实体在做mapper配置的时候就不用写全名了)
logging:
  level:
    com.smile67: debug